<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="makeFiles" nsURI="makeFiles" nsPrefix="makeFiles">
  <eClassifiers xsi:type="ecore:EClass" name="MakeFile">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" upperBound="-1"
        eType="#//Target" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//Dependencies" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" upperBound="-1"
        eType="#//Commands" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" upperBound="-1"
        eType="#//Comment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="makes" upperBound="-1"
        eType="#//Make" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Make">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Target" eOpposite="#//Target/makesUsedIn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dependencies" upperBound="-1"
        eType="#//Dependencies" eOpposite="#//Dependencies/makesUsedIn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" upperBound="-1"
        eType="#//Commands" eOpposite="#//Commands/makesUsedIn"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comments" upperBound="-1"
        eType="#//Comment" eOpposite="#//Comment/makesUsedIn"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Target">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="makesUsedIn" upperBound="-1"
        eType="#//Make" eOpposite="#//Make/target"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dependencies">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="makesUsedIn" upperBound="-1"
        eType="#//Make" eOpposite="#//Make/dependencies"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Commands">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="makesUsedIn" upperBound="-1"
        eType="#//Make" eOpposite="#//Make/commands"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Comment">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="makesUsedIn" upperBound="-1"
        eType="#//Make" eOpposite="#//Make/comments"/>
  </eClassifiers>
</ecore:EPackage>
